#ifndef FREERDP_BUILD_CONFIG_H
#define FREERDP_BUILD_CONFIG_H

#define FREERDP_DATA_PATH "${FREERDP_DATA_PATH}"
#define FREERDP_KEYMAP_PATH "${FREERDP_KEYMAP_PATH}"
#define FREERDP_PLUGIN_PATH "${FREERDP_PLUGIN_PATH}"

#define FREERDP_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"

#define FREERDP_LIBRARY_PATH "${FREERDP_LIBRARY_PATH}"

#define FREERDP_ADDIN_PATH "${FREERDP_ADDIN_PATH}"

#define FREERDP_SHARED_LIBRARY_SUFFIX "${CMAKE_SHARED_LIBRARY_SUFFIX}"
#define FREERDP_SHARED_LIBRARY_PREFIX  "${CMAKE_SHARED_LIBRARY_PREFIX}"

#define FREERDP_VENDOR_STRING "${VENDOR}"
#define FREERDP_PRODUCT_STRING "${PRODUCT}"

#endif /* FREERDP_BUILD_CONFIG_H */
