cmake . -B"./Build/x86" -G"Visual Studio 17 2022" -AWin32^
	-DOPENSSL_ROOT_DIR="../OpenSSL-VC-32"^
	-DCMAKE_INSTALL_PREFIX="./Install/x86"^
	-DMSVC_RUNTIME="static"^
	-DBUILD_SHARED_LIBS=OFF^
	-DWITH_CLIENT_INTERFACE=ON^
	-DBUILTIN_CHANNELS=OFF^
	-DWITH_CHANNELS=OFF^
	-DWITH_MEDIA_FOUNDATION=OFF
pause
