
set(MINWIN_LAYER "1")
set(MINWIN_GROUP "core")
set(MINWIN_MAJOR_VERSION "1")
set(MINWIN_MINOR_VERSION "0")
set(MINWIN_SHORT_NAME "ncrypt")
set(MINWIN_LONG_NAME "NCrypt Functions")
set(MODULE_LIBRARY_NAME "ncrypt")

