
set(MINWIN_LAYER "0")
set(MINWIN_GROUP "none")
set(MINWIN_MAJOR_VERSION "0")
set(MINWIN_MINOR_VERSION "0")
set(MINWIN_SHORT_NAME "winhttp")
set(MINWIN_LONG_NAME "Windows HTTP (WinHTTP)")
set(MODULE_LIBRARY_NAME "${MINWIN_SHORT_NAME}")

