/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "CREDSSP"
 * 	found in "credssp.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names`
 */

#ifndef	_NegoData_H_
#define	_NegoData_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NegoDataItem;

/* NegoData */
typedef struct NegoData {
	A_SEQUENCE_OF(struct NegoDataItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NegoData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NegoData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NegoDataItem.h"

#endif	/* _NegoData_H_ */
