/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "CREDSSP"
 * 	found in "credssp.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names`
 */

#include "asn_internal.h"

#include "TSPasswordCreds.h"

static asn_TYPE_member_t asn_MBR_TSPasswordCreds_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TSPasswordCreds, domainName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"domainName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TSPasswordCreds, userName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"userName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TSPasswordCreds, password),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"password"
		},
};
static ber_tlv_tag_t asn_DEF_TSPasswordCreds_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TSPasswordCreds_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* domainName at 27 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* userName at 28 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* password at 29 */
};
static asn_SEQUENCE_specifics_t asn_SPC_TSPasswordCreds_specs_1 = {
	sizeof(struct TSPasswordCreds),
	offsetof(struct TSPasswordCreds, _asn_ctx),
	asn_MAP_TSPasswordCreds_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TSPasswordCreds = {
	"TSPasswordCreds",
	"TSPasswordCreds",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TSPasswordCreds_tags_1,
	sizeof(asn_DEF_TSPasswordCreds_tags_1)
		/sizeof(asn_DEF_TSPasswordCreds_tags_1[0]), /* 1 */
	asn_DEF_TSPasswordCreds_tags_1,	/* Same as above */
	sizeof(asn_DEF_TSPasswordCreds_tags_1)
		/sizeof(asn_DEF_TSPasswordCreds_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TSPasswordCreds_1,
	3,	/* Elements count */
	&asn_SPC_TSPasswordCreds_specs_1	/* Additional specs */
};

