/*
 * Generated by asn1c-0.9.22.1409 (http://lionet.info/asn1c)
 * From ASN.1 module "CREDSSP"
 * 	found in "credssp.asn1"
 * 	`asn1c -fnative-types -fskeletons-copy -fcompound-names`
 */

#ifndef	_TSSmartCardCreds_H_
#define	_TSSmartCardCreds_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"
#include "TSCspDataDetail.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TSSmartCardCreds */
typedef struct TSSmartCardCreds {
	OCTET_STRING_t	 pin;
	TSCspDataDetail_t	 cspData;
	OCTET_STRING_t	*userHint	/* OPTIONAL */;
	OCTET_STRING_t	*domainHint	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TSSmartCardCreds_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TSSmartCardCreds;

#ifdef __cplusplus
}
#endif

#endif	/* _TSSmartCardCreds_H_ */
