set (WITH_SERVER ON CACHE BOOL "qa default")
set (WITH_SAMPLE ON CACHE BOOL "qa default")
set (WITH_VERBOSE_WINPR_ASSERT OFF CACHE BOOL "qa default")
set (BUILD_SHARED_LIBS OFF CACHE BOOL "qa default")
