
set(MINWIN_LAYER "0")
set(MINWIN_GROUP "none")
set(MINWIN_MAJOR_VERSION "0")
set(MINWIN_MINOR_VERSION "0")
set(MINWIN_SHORT_NAME "msasn1")
set(MINWIN_LONG_NAME "Microsoft ASN.1")
set(MODULE_LIBRARY_NAME "${MINWIN_SHORT_NAME}")

