set(_freerdp_toolchain "${CMAKE_CURRENT_LIST_DIR}/suse-sanitizer-toolchain.cmake")

set(WITH_SANITIZE_ADDRESS OFF CACHE BOOL "" FORCE)
set(WITH_SANITIZE_MEMORY OFF CACHE BOOL "" FORCE)
set(WITH_SANITIZE_THREAD OFF CACHE BOOL "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now" CACHE STRING "" FORCE)
include("${_freerdp_toolchain}")

foreach(_freerdp_var CMAKE_EXE_LINKER_FLAGS CMAKE_SHARED_LINKER_FLAGS)
  if(NOT "${${_freerdp_var}}" MATCHES "--no-undefined")
    message(FATAL_ERROR "${_freerdp_var} lost --no-undefined without sanitizer")
  endif()
endforeach()

set(WITH_SANITIZE_ADDRESS ON CACHE BOOL "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now" CACHE STRING "" FORCE)
set(CMAKE_MODULE_LINKER_FLAGS "-Wl,--as-needed" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "-Wl,--as-needed -Wl,--no-undefined -Wl,-z,now" CACHE STRING "" FORCE)
include("${_freerdp_toolchain}")

foreach(_freerdp_var CMAKE_EXE_LINKER_FLAGS CMAKE_MODULE_LINKER_FLAGS CMAKE_SHARED_LINKER_FLAGS)
  if("${${_freerdp_var}}" MATCHES "--no-undefined")
    message(FATAL_ERROR "${_freerdp_var} still has --no-undefined with sanitizer")
  endif()
  if(NOT "${${_freerdp_var}}" MATCHES "--as-needed")
    message(FATAL_ERROR "${_freerdp_var} lost --as-needed")
  endif()
endforeach()

foreach(_freerdp_var CMAKE_EXE_LINKER_FLAGS CMAKE_SHARED_LINKER_FLAGS)
  if(NOT "${${_freerdp_var}}" MATCHES "-Wl,-z,now")
    message(FATAL_ERROR "${_freerdp_var} lost -Wl,-z,now")
  endif()
endforeach()
