
find_package(PkgConfig REQUIRED)

set(FREERDP_PREFIX_PATH
    "${DEPS_INSTALL_DIR};${DEPS_INSTALL_DIR}/${CMAKE_INSTALL_LIBDIR}/cmake;${DEPS_INSTALL_DIR}/${CMAKE_INSTALL_LIBDIR};${DEPS_INSTALL_DIR}/${CMAKE_INSTALL_LIBDIR}/pkgconfig;${DEPS_INSTALL_DIR};${DEPS_INSTALL_DIR}/${CMAKE_INSTALL_DATAROOTDIR}"
)

set(FREERDP_EXTRA_CMAKE_ARGS
    -DWITHOUT_WINPR_3x_DEPRECATED:BOOL=ON
    -DWITHOUT_FREERDP_3x_DEPRECATED:BOOL=ON
    -DWITH_CLIENT:BOOL=ON
    -DWITH_CLIENT_IOS:BOOL=OFF
    -DWITH_CLIENT_SDL:BOOL=OFF
    -DWITH_SAMPLE:BOOL=OFF
    -DWITH_SERVER:BOOL=OFF
    -DWITH_MANPAGES:BOOL=OFF
    -DWITH_SYSTEMD:BOOL=OFF
    -DPKG_CONFIG_EXECUTABLE:FILEPATH=${PKG_CONFIG_EXECUTABLE}
    -DWITH_INTERNAL_RC4:BOOL=ON
    -DWITH_INTERNAL_MD4:BOOL=ON
    -DWITH_INTERNAL_MD5:BOOL=ON
    -DWITH_OPENSSL:BOOL=${WITH_OPENSSL}
    -DFREERDP_IOS_EXTERNAL_SSL_PATH:PATH=${DEPS_INSTALL_DIR}
    -DWITH_VIDEOTOOLBOX:BOOL=ON
    -DWITH_FFMPEG:BOOL=${WITH_FFMPEG}
    -DWITH_VIDEO_FFMPEG:BOOL=${WITH_FFMPEG}
    -DWITH_DSP_FFMPEG:BOOL=OFF
    -DWITH_SWSCALE:BOOL=OFF
    ${IOS_FFMPEG_ARGS}
)

if(DEFINED CMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM)
  list(APPEND FREERDP_EXTRA_CMAKE_ARGS
       -DCMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM:STRING=${CMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM}
  )
endif()
if(DEFINED CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_STYLE)
  list(APPEND FREERDP_EXTRA_CMAKE_ARGS
       -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_STYLE:STRING=${CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_STYLE}
  )
endif()
if(DEFINED CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY)
  list(APPEND FREERDP_EXTRA_CMAKE_ARGS
       -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY:STRING=${CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY}
  )
endif()

ExternalProject_Add(
  freerdp
  DOWNLOAD_EXTRACT_TIMESTAMP OFF
  SOURCE_DIR ${FREERDP_SOURCE_DIR}
  CMAKE_ARGS ${IOS_CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX:PATH=${DEPS_INSTALL_DIR}
             -DCMAKE_INSTALL_LIBDIR:STRING=${CMAKE_INSTALL_LIBDIR} -DCMAKE_INSTALL_NAME_DIR:STRING=@rpath
             -DCMAKE_PREFIX_PATH:PATH=${FREERDP_PREFIX_PATH} ${FREERDP_EXTRA_CMAKE_ARGS}
  DEPENDS ${IOS_NATIVE_DEPS}
  BUILD_BYPRODUCTS
    ${DEPS_INSTALL_DIR}/${CMAKE_INSTALL_LIBDIR}/libfreerdp3.3.dylib
    ${DEPS_INSTALL_DIR}/${CMAKE_INSTALL_LIBDIR}/libfreerdp-client3.3.dylib
    ${DEPS_INSTALL_DIR}/${CMAKE_INSTALL_LIBDIR}/libwinpr3.3.dylib
)

file(MAKE_DIRECTORY ${DEPS_INSTALL_DIR}/include ${DEPS_INSTALL_DIR}/include/freerdp3 ${DEPS_INSTALL_DIR}/include/winpr3)

add_library(freerdp3-lib SHARED IMPORTED GLOBAL)
set_target_properties(
  freerdp3-lib PROPERTIES IMPORTED_LOCATION "${DEPS_INSTALL_DIR}/${CMAKE_INSTALL_LIBDIR}/libfreerdp3.3.dylib"
                          INTERFACE_INCLUDE_DIRECTORIES "${DEPS_INSTALL_DIR}/include/freerdp3"
)
add_dependencies(freerdp3-lib freerdp)

add_library(freerdp-client3-lib SHARED IMPORTED GLOBAL)
set_target_properties(
  freerdp-client3-lib
  PROPERTIES IMPORTED_LOCATION "${DEPS_INSTALL_DIR}/${CMAKE_INSTALL_LIBDIR}/libfreerdp-client3.3.dylib"
             INTERFACE_INCLUDE_DIRECTORIES "${DEPS_INSTALL_DIR}/include/freerdp3"
)
add_dependencies(freerdp-client3-lib freerdp)

add_library(winpr3-lib SHARED IMPORTED GLOBAL)
set_target_properties(
  winpr3-lib PROPERTIES IMPORTED_LOCATION "${DEPS_INSTALL_DIR}/${CMAKE_INSTALL_LIBDIR}/libwinpr3.3.dylib"
                        INTERFACE_INCLUDE_DIRECTORIES "${DEPS_INSTALL_DIR}/include/winpr3"
)
add_dependencies(winpr3-lib freerdp)
