include(ExternalProject)
include(DepVersions)

ExternalProject_Add(
  uriparser
  DOWNLOAD_EXTRACT_TIMESTAMP OFF
  URL https://github.com/uriparser/uriparser/releases/download/uriparser-${URIPARSER_VERSION}/uriparser-${URIPARSER_VERSION}.tar.xz
  URL_HASH ${URIPARSER_HASH}
  LIST_SEPARATOR |
  CMAKE_CACHE_ARGS ${IOS_CMAKE_CACHE_ARGS}
  CMAKE_ARGS ${IOS_CMAKE_ARGS} -DURIPARSER_BUILD_DOCS:BOOL=OFF -DURIPARSER_BUILD_TESTS:BOOL=OFF
             -DURIPARSER_BUILD_TOOLS:BOOL=OFF -DENABLE_STRICT_TRY_COMPILE:BOOL=ON
)
