include(GNUInstallDirs)

set(DEPS_INSTALL_DIR "${CMAKE_BINARY_DIR}/deps")
file(MAKE_DIRECTORY ${DEPS_INSTALL_DIR})

option(WITH_OPENSSL "Build and enable OpenSSL" ON)
option(WITH_FFMPEG "Build and enable FFmpeg codec support" ON)

get_filename_component(_toolchain_abs "${CMAKE_TOOLCHAIN_FILE}" ABSOLUTE BASE_DIR "${CMAKE_BINARY_DIR}")

set(IOS_CMAKE_ARGS
    -DCMAKE_TOOLCHAIN_FILE:FILEPATH=${_toolchain_abs} -DPLATFORM:STRING=${PLATFORM}
    -DDEPLOYMENT_TARGET:STRING=${DEPLOYMENT_TARGET} -DIOS_TARGET_SDK:STRING=${DEPLOYMENT_TARGET}
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE} -DBUILD_SHARED_LIBS:BOOL=ON
)

set(IOS_NATIVE_DEPS "")

if(WITH_OPENSSL)
  include(ExternalOpenSSL)
  list(APPEND IOS_NATIVE_DEPS openssl)
  set(OPENSSL_INCLUDE_DIR ${DEPS_INSTALL_DIR}/include)
  set(OPENSSL_SSL_LIBRARY ${DEPS_INSTALL_DIR}/${CMAKE_INSTALL_LIBDIR}/libssl.a)
  set(OPENSSL_CRYPTO_LIBRARY ${DEPS_INSTALL_DIR}/${CMAKE_INSTALL_LIBDIR}/libcrypto.a)
  set(OPENSSL_LIBRARIES ${OPENSSL_SSL_LIBRARY} ${OPENSSL_CRYPTO_LIBRARY})
  set(OPENSSL_FOUND ON)
endif()

set(IOS_FFMPEG_ARGS "")
if(WITH_FFMPEG)
  include(ExternalFFmpeg)
  list(APPEND IOS_NATIVE_DEPS ffmpeg)
  set(AVCODEC_INCLUDE_DIRS ${DEPS_INSTALL_DIR}/FFmpeg.framework/Headers)
  set(AVUTIL_INCLUDE_DIRS ${DEPS_INSTALL_DIR}/FFmpeg.framework/Headers)
  set(AVCODEC_LIBRARIES ${DEPS_INSTALL_DIR}/FFmpeg.framework/FFmpeg)
  set(AVUTIL_LIBRARIES ${DEPS_INSTALL_DIR}/FFmpeg.framework/FFmpeg)
  set(IOS_FFMPEG_ARGS
      -DAVCODEC_INCLUDE_DIRS:PATH=${AVCODEC_INCLUDE_DIRS} -DAVUTIL_INCLUDE_DIRS:PATH=${AVUTIL_INCLUDE_DIRS}
      -DAVCODEC_LIBRARIES:FILEPATH=${AVCODEC_LIBRARIES} -DAVUTIL_LIBRARIES:FILEPATH=${AVUTIL_LIBRARIES}
  )
endif()

include(ExternalFreeRDP)
