
set(MINWIN_LAYER "1")
set(MINWIN_GROUP "core")
set(MINWIN_MAJOR_VERSION "1")
set(MINWIN_MINOR_VERSION "0")
set(MINWIN_SHORT_NAME "input")
set(MINWIN_LONG_NAME "Input Functions")
set(MODULE_LIBRARY_NAME "input")

