
set(MINWIN_LAYER "0")
set(MINWIN_GROUP "none")
set(MINWIN_MAJOR_VERSION "0")
set(MINWIN_MINOR_VERSION "0")
set(MINWIN_SHORT_NAME "smartcard")
set(MINWIN_LONG_NAME "Smart Card API")
set(MODULE_LIBRARY_NAME "${MINWIN_SHORT_NAME}")

