TestOpenH264ASM: TestOpenH264ASM.c.o h264.c.o h264_ssse3.asm.o #h264.asm.o
	gcc -o TestOpenH264ASM TestOpenH264ASM.c.o h264.c.o h264_ssse3.asm.o #h264.asm.o

h264_ssse3.asm.o: ../h264_ssse3_x32.asm
	nasm -f elf64 -o h264_ssse3.asm.o ../h264_ssse3_x32.asm
	
h264.asm.o: ../h264_x32.asm
	nasm -f elf64 -o h264.asm.o ../h264_x32.asm

TestOpenH264ASM.c.o: TestOpenH264ASM.c
	gcc -c -o TestOpenH264ASM.c.o TestOpenH264ASM.c

h264.c.o: ../h264.c
	gcc -c -o h264.c.o ../h264.c

clean:
	rm -f TestOpenH264ASM TestOpenH264ASM.c.o h264_ssse3.asm.o h264.c.o h264.asm.o
