TestOpenH264: TestOpenH264ASM.c.o h264.c.o h264_ssse3.c.o
	gcc -o TestOpenH264 TestOpenH264ASM.c.o h264.c.o h264_ssse3.c.o -lwinpr

h264_ssse3.c.o: ../h264_ssse3.c
	gcc -c -O3 -o h264_ssse3.c.o ../h264_ssse3.c -mssse3

TestOpenH264ASM.c.o: TestOpenH264ASM.c
	gcc -c -o TestOpenH264ASM.c.o TestOpenH264ASM.c

h264.c.o: ../h264.c
	gcc -c -o h264.c.o ../h264.c

clean:
	rm -f TestOpenH264 TestOpenH264ASM.c.o h264_ssse3.asm.o h264.c.o h264.asm.o
