TestOpenH264ASM: h264_ssse3.asm.o TestOpenH264ASM.c.o h264.c.o
	gcc -o TestOpenH264ASM h264_ssse3.asm.o TestOpenH264ASM.c.o h264.c.o

h264_ssse3.asm.o: ../h264_ssse3_x64.asm
	nasm -f elf64 -o h264_ssse3.asm.o ../h264_ssse3_x64.asm
	
h264.asm.o: ../h264.asm
	nasm -f elf64 -o h264.asm.o ../h264.asm

TestOpenH264ASM.c.o: TestOpenH264ASM.c
	gcc -c -o TestOpenH264ASM.c.o TestOpenH264ASM.c

h264.c.o: ../h264.c
	gcc -c -O3 -o h264.c.o ../h264.c

clean:
	rm -f TestOpenH264ASM TestOpenH264ASM.c.o h264_ssse3.asm.o h264.c.o h264.asm.o
	
old: h264.asm.o TestOpenH264ASM.c.o h264.c.o
	gcc -o TestOpenH264ASM h264.asm.o TestOpenH264ASM.c.o h264.c.o
