include(ExternalProject)

set(JPEG_VERSION "3.1.4")

ExternalProject_Add(
  jpeg SOURCE_DIR ${CMAKE_SOURCE_DIR}/external/jpeg GIT_REPOSITORY https://github.com/libjpeg-turbo/libjpeg-turbo.git
  GIT_TAG ${JPEG_VERSION} GIT_SHALLOW TRUE UPDATE_DISCONNECTED ON
  CMAKE_ARGS ${ANDROID_CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX:PATH=${DEPS_INSTALL_DIR}
             -DCMAKE_INSTALL_LIBDIR:STRING=${CMAKE_INSTALL_LIBDIR} -DWITH_TURBOJPEG:BOOL=OFF -DENABLE_TESTING:BOOL=OFF
             -DWITH_TOOLS:BOOL=OFF
)
