include(ExternalProject)

set(LIBPNG_VERSION "v1.6.58")

ExternalProject_Add(
  libpng SOURCE_DIR ${CMAKE_SOURCE_DIR}/external/libpng GIT_REPOSITORY https://github.com/pnggroup/libpng.git
  GIT_TAG ${LIBPNG_VERSION} GIT_SHALLOW TRUE UPDATE_DISCONNECTED ON
  CMAKE_ARGS ${ANDROID_CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX:PATH=${DEPS_INSTALL_DIR}
             -DCMAKE_INSTALL_LIBDIR:STRING=${CMAKE_INSTALL_LIBDIR} -DPNG_TESTS:BOOL=OFF -DPNG_TOOLS:BOOL=OFF
)
