include(ExternalProject)

set(URIPARSER_VERSION "uriparser-1.0.2")

ExternalProject_Add(
  uriparser SOURCE_DIR ${CMAKE_SOURCE_DIR}/external/uriparser GIT_REPOSITORY https://github.com/uriparser/uriparser.git
  GIT_TAG ${URIPARSER_VERSION} GIT_SHALLOW TRUE UPDATE_DISCONNECTED ON
  CMAKE_ARGS ${ANDROID_CMAKE_ARGS} -DCMAKE_INSTALL_PREFIX:PATH=${DEPS_INSTALL_DIR}
             -DCMAKE_INSTALL_LIBDIR:STRING=${CMAKE_INSTALL_LIBDIR} -DURIPARSER_BUILD_DOCS:BOOL=OFF
             -DURIPARSER_BUILD_TESTS:BOOL=OFF -DURIPARSER_BUILD_TOOLS:BOOL=OFF
)
