include(ExternalProject)

set(CJSON_VERSION "v1.7.19")

ExternalProject_Add(
  cjson
  SOURCE_DIR ${CMAKE_SOURCE_DIR}/external/cjson
  GIT_REPOSITORY https://github.com/DaveGamble/cJSON.git
  GIT_TAG ${CJSON_VERSION}
  GIT_SHALLOW TRUE
  UPDATE_DISCONNECTED ON
  CMAKE_ARGS ${ANDROID_CMAKE_ARGS}
             -DCMAKE_INSTALL_PREFIX:PATH=${DEPS_INSTALL_DIR}
             -DCMAKE_INSTALL_LIBDIR:STRING=${CMAKE_INSTALL_LIBDIR}
             -DENABLE_CJSON_TEST:BOOL=OFF
             -DENABLE_HIDDEN_SYMBOLS:BOOL=OFF
             -DENABLE_CJSON_UNINSTALL:BOOL=OFF
             -DCMAKE_POLICY_VERSION_MINIMUM:STRING=3.5
)
