# BSD
if(${CMAKE_SYSTEM_NAME} MATCHES "BSD")
    set(BSD TRUE CACHE INTERNAL "BSD detection")
	if(${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD")
        set(FREEBSD TRUE CACHE INTERNAL "BSD detection")
	endif()
	if(${CMAKE_SYSTEM_NAME} MATCHES "kFreeBSD")
        set(KFREEBSD TRUE CACHE INTERNAL "BSD detection")
	endif()
	if(${CMAKE_SYSTEM_NAME} MATCHES "OpenBSD")
        set(OPENBSD TRUE CACHE INTERNAL "BSD detection")
	endif()
endif()

if(${CMAKE_SYSTEM_NAME} MATCHES "DragonFly")
    set(BSD TRUE CACHE INTERNAL "BSD detection")
    set(FREEBSD TRUE CACHE INTERNAL "BSD detection")
endif()
