# - Try to find the AOM library
# Once done this will define
#
#  AOM_ROOT - A list of search hints
#
#  AOM_FOUND - system has AOM
#  AOM_INCLUDE_DIRS - the AOM include directory
#  AOM_LIBRARIES - libaom library

set(AOM_MIN_VERSION "2.0")

if(UNIX AND NOT ANDROID)
  find_package(PkgConfig QUIET)
  pkg_check_modules(PC_AOM QUIET aom)
endif(UNIX AND NOT ANDROID)

if(AOM_INCLUDE_DIR AND AOM_LIBRARY)
  set(AOM_FIND_QUIETLY TRUE)
endif(AOM_INCLUDE_DIR AND AOM_LIBRARY)

find_path(AOM_INCLUDE_DIR NAMES aom/aom.h PATH_SUFFIXES include HINTS ${AOM_ROOT} ${PC_AOM_INCLUDE_DIRS})
find_library(AOM_LIBRARY NAMES aom PATH_SUFFIXES lib HINTS ${AOM_ROOT} ${PC_AOM_LIBRARY_DIRS})

set(AOM_VERSION ${PC_AOM_VERSION})
set(AOM_VERSION_OK FALSE)
if(AOM_VERSION AND NOT AOM_VERSION VERSION_LESS AOM_MIN_VERSION)
  set(AOM_VERSION_OK TRUE)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
  aom REQUIRED_VARS AOM_LIBRARY AOM_INCLUDE_DIR AOM_VERSION_OK
  VERSION_VAR AOM_VERSION REASON_FAILURE_MESSAGE "AOM version ${AOM_MIN_VERSION} or newer is required"
)

if(aom_FOUND)
  set(AOM_FOUND ON CACHE BOOL "AOM" FORCE)
  set(aom_FOUND ON CACHE BOOL "aom" FORCE)
  set(AOM_LIBRARIES ${AOM_LIBRARY} CACHE STRING "AOM" FORCE)
  set(AOM_INCLUDE_DIRS ${AOM_INCLUDE_DIR} CACHE STRING "AOM" FORCE)
  set(AOM_VERSION ${AOM_VERSION} CACHE STRING "AOM" FORCE)
else()
  set(AOM_FOUND OFF CACHE BOOL "AOM" FORCE)
  set(aom_FOUND OFF CACHE BOOL "aom" FORCE)
endif(aom_FOUND)

if(AOM_FOUND)
  if(NOT AOM_FIND_QUIETLY)
    message(STATUS "Found AOM: ${AOM_LIBRARIES} (${AOM_VERSION})")
  endif(NOT AOM_FIND_QUIETLY)
else(AOM_FOUND)
  if(aom_FIND_REQUIRED)
    message(FATAL_ERROR "AOM was not found")
  endif(aom_FIND_REQUIRED)
endif(AOM_FOUND)

mark_as_advanced(AOM_INCLUDE_DIRS AOM_LIBRARIES AOM_FOUND aom_FOUND AOM_VERSION)
