function(install_freerdp_man manpage section)
 if(WITH_MANPAGES)
   if(OPENBSD OR FREEBSD)
       install(FILES ${manpage} DESTINATION man/man${section})
    else()
       install(FILES ${manpage} DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/man/man${section})
   endif()
 endif()
endfunction()
