include(ExternalProject)

get_filename_component(OHOS_COMPILER_BIN_DIR "${CMAKE_C_COMPILER}" DIRECTORY)
get_filename_component(OHOS_LLVM_DIR "${OHOS_COMPILER_BIN_DIR}" DIRECTORY)
get_filename_component(OHOS_NATIVE_DIR "${OHOS_LLVM_DIR}" DIRECTORY)
set(OHOS_TOOLCHAIN_FILE "${OHOS_NATIVE_DIR}/build/cmake/ohos.toolchain.cmake")

if(NOT EXISTS "${OHOS_TOOLCHAIN_FILE}")
  message(FATAL_ERROR "ExternalFreeRDP: ohos.toolchain.cmake not found at ${OHOS_TOOLCHAIN_FILE}")
endif()

set(FREERDP_INSTALL_DIR "${CMAKE_BINARY_DIR}/deps/freerdp")

set(FREERDP_CMAKE_ARGS
    -DCMAKE_TOOLCHAIN_FILE:FILEPATH=${OHOS_TOOLCHAIN_FILE}
    -DOHOS_ARCH:STRING=${OHOS_ARCH}
    -DOHOS_STL:STRING=c++_shared
    -DCMAKE_MAKE_PROGRAM:FILEPATH=${CMAKE_MAKE_PROGRAM}
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX:PATH=${FREERDP_INSTALL_DIR}
    -DCMAKE_INSTALL_LIBDIR:STRING=lib
    -DBUILD_SHARED_LIBS:BOOL=OFF
    -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON
    -DOPENSSL_ROOT_DIR:PATH=${OPENSSL_INSTALL_DIR}
    -DOPENSSL_INCLUDE_DIR:PATH=${OPENSSL_INSTALL_DIR}/include
    -DOPENSSL_SSL_LIBRARY:FILEPATH=${OPENSSL_INSTALL_DIR}/libssl.a
    -DOPENSSL_CRYPTO_LIBRARY:FILEPATH=${OPENSSL_INSTALL_DIR}/libcrypto.a
    -DWITH_OPENSSL:BOOL=ON
    -DWITH_CLIENT:BOOL=ON
    -DWITH_CLIENT_COMMON:BOOL=ON
    -DWITH_CLIENT_CHANNELS:BOOL=ON
    -DWITH_SERVER:BOOL=OFF
    -DWITH_SAMPLE:BOOL=OFF
    -DWITH_CLIENT_SDL:BOOL=OFF
    -DWITH_X11:BOOL=OFF
    -DWITH_WAYLAND:BOOL=OFF
    -DWITH_MANPAGES:BOOL=OFF
    -DWITH_PULSE:BOOL=OFF
    -DWITH_CUPS:BOOL=OFF
    -DWITH_FFMPEG:BOOL=OFF
    -DWITH_DSP_FFMPEG:BOOL=OFF
    -DWITH_VIDEO_FFMPEG:BOOL=OFF
    -DWITH_SWSCALE:BOOL=OFF
    -DWITH_KRB5:BOOL=OFF
    -DWITH_UNICODE_BUILTIN:BOOL=ON
    -DWITH_FUSE:BOOL=OFF
    -DCHANNEL_URBDRC:BOOL=OFF
    -DCHANNEL_URBDRC_CLIENT:BOOL=OFF
    -DBUILD_TESTING:BOOL=OFF
    -DWITH_INTERNAL_RC4:BOOL=ON
    -DWITH_INTERNAL_MD4:BOOL=ON
    -DWITH_INTERNAL_MD5:BOOL=ON
)

ExternalProject_Add(
  freerdp SOURCE_DIR ${FREERDP_SOURCE_DIR} CMAKE_COMMAND ${CMAKE_COMMAND} CMAKE_ARGS ${FREERDP_CMAKE_ARGS}
  DEPENDS openssl BUILD_COMMAND ${CMAKE_COMMAND} --build <BINARY_DIR> INSTALL_COMMAND ${CMAKE_COMMAND} --build
                                                                                      <BINARY_DIR> --target install
  COMMAND ${CMAKE_COMMAND} -DFREERDP_LIB_DIR=${FREERDP_INSTALL_DIR}/lib -P
          ${CMAKE_CURRENT_LIST_DIR}/CollectArchives.cmake
  BUILD_BYPRODUCTS ${FREERDP_INSTALL_DIR}/lib/libfreerdp3.a ${FREERDP_INSTALL_DIR}/lib/libfreerdp-client3.a
                   ${FREERDP_INSTALL_DIR}/lib/libwinpr3.a
)

file(MAKE_DIRECTORY ${FREERDP_INSTALL_DIR}/include/freerdp3)
file(MAKE_DIRECTORY ${FREERDP_INSTALL_DIR}/include/winpr3)
file(MAKE_DIRECTORY ${FREERDP_INSTALL_DIR}/lib)

set(FREERDP_ARCHIVES_RSP "${FREERDP_INSTALL_DIR}/lib/freerdp_archives.rsp")
file(WRITE ${FREERDP_ARCHIVES_RSP}
     "${FREERDP_INSTALL_DIR}/lib/libfreerdp3.a
${FREERDP_INSTALL_DIR}/lib/libfreerdp-client3.a
${FREERDP_INSTALL_DIR}/lib/libwinpr3.a
"
)
