name: Fuzzing testing

on:
  workflow_dispatch:
    branches: [ master, stable* ]
  pull_request:
    branches: [ master, stable* ]
  schedule:
  - cron: "0 3 21 * *"

jobs:
  fuzzing:
    if: github.repository == 'FreeRDP/FreeRDP'

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined]

    steps:
      - uses: actions/checkout@v4

      - name: Build fuzzers (${{ matrix.sanitizer }})
        id: build
        uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
        with:
          oss-fuzz-project-name: 'freerdp'
          dry-run: false
          sanitizer: ${{ matrix.sanitizer }}
      - name: Run fuzzers (${{ matrix.sanitizer }})
        uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
        with:
          oss-fuzz-project-name: 'freerdp'
          fuzz-seconds: 600
          dry-run: false
          sanitizer: ${{ matrix.sanitizer }}
      - name: Upload crash
        uses: actions/upload-artifact@v3
        if: failure() && steps.build.outcome == 'success'
        with:
          name: ${{ matrix.sanitizer }}-artifacts
          retention-days: 21
          path: ./out/artifacts
